### ISSUE TITLE
Italian date 

### ISSUE THREAD

**Issue by wifi75** [stanoba/ospiLCD#1]
Hello how is possible set fate in italian?

**Comment by stanoba** [comment]
Hi wifi75, yes it is. Check latest **ospiLCD.py** script. I have added option to set locale you want. At first, run "_**sudo raspi-config**_", go to **_Internationalisation Options_** / **_Change Locale_** and select your locale (eg. it_IT.UTF-8). Then edit ospiLCD.py script and set **_date_locale_** parameter to '**_it_IT.UTF-8_**' (same as in raspi-config). If you like to change day/month format, edit line 131 and set time format to '**%H:%M %a %d.%m.**' or format you want.

**Comment by wifi75** [comment]
thank you I will try.

**Comment by wifi75** [comment]
thank you I will try.

**Comment by wifi75** [comment]
Hello date_locale in found inside ospiLCD.py...

**Comment by wifi75** [comment]
Ok now is ok, 
just add 

date_locale = 'it_IT.UTF-8'  # Set to your Raspberry pi locale eg. 'en_GB.UTF-8' or 'it_IT.UTF-8'

thank you

**Comment by wifi75** [comment]
hello date is only in english also after insert 
date_locale = 'it_IT.UTF-8'


why?
