### ISSUE TITLE
LCD display 20x4 

### ISSUE THREAD

**Issue by wifi75** [stanoba/ospiLCD#4]
Hello sir, 
i try to buy new lcd 20x4, I removed 2 resistor 4.7, than I check the correct address with command: 
sudo i2cdetect -y 1 and found this address:  3f
than I change configuration nano /home/pi/ospiLCD.py:

LCD_i2c_expander = 'PCF8574'  # PCF8574 (default, ebay), MCP23008 (used in Adafruit I2C LCD backpack) or MCP23017
LCD_i2c_address = 0x3f  # LCD I2C address (default 0x27)
LCD_cols = 20  # LCD columns (16 or 20)
LCD_rows = 4   # LCD rows (2 or 4)

I tryed also to change parameter LCD_i2c_expander with: PCF8574, or MCP23008 or MCP23017,
but not caracter displayed only blue color light.

why?

But the address 0x3f it very correct?

**Comment by stanoba** [comment]
Hello, could you post an image of the LCDs backpack and output of "sudo i2cdetect -y 1" command? We should identify expander first.

**Comment by wifi75** [comment]
yes:
![1](https://user-images.githubusercontent.com/31816231/32267560-f09e33d6-beeb-11e7-9b07-a5bfffe16440.PNG)

**Comment by wifi75** [comment]
![foto ](https://i.imgur.com/zQCxzGW.jpg)

**Comment by wifi75** [comment]
sorry sir, the problem it was only the contrast trimmer...
now is ok! 

sorry again

**Comment by stanoba** [comment]
Thanks :)
